// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/quydmfl/niveau-test/internal/handler"
	"github.com/quydmfl/niveau-test/internal/job"
	"github.com/quydmfl/niveau-test/internal/repository"
	"github.com/quydmfl/niveau-test/internal/server"
	"github.com/quydmfl/niveau-test/internal/service"
	"github.com/quydmfl/niveau-test/pkg/app"
	"github.com/quydmfl/niveau-test/pkg/jwt"
	"github.com/quydmfl/niveau-test/pkg/log"
	"github.com/quydmfl/niveau-test/pkg/server/http"
	"github.com/quydmfl/niveau-test/pkg/sid"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	productRepository := repository.NewProductRepository(repositoryRepository)
	categoryRepository := repository.NewCategoryRepository(repositoryRepository)
	documentsRepository := repository.NewDocumentsRepository(repositoryRepository)
	supplierRepository := repository.NewSupplierRepository(repositoryRepository)
	productService := service.NewProductService(serviceService, productRepository, categoryRepository, documentsRepository, supplierRepository)
	productHandler := handler.NewProductHandler(handlerHandler, productService)
	categoryService := service.NewCategoryService(serviceService, categoryRepository)
	categoryHandler := handler.NewCategoryHandler(handlerHandler, categoryService)
	supplierService := service.NewSupplierService(serviceService, supplierRepository)
	supplierHandler := handler.NewSupplierHandler(handlerHandler, supplierService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler, productHandler, categoryHandler, supplierHandler)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewProductRepository, repository.NewSupplierRepository, repository.NewCategoryRepository, repository.NewDocumentsRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewProductService, service.NewSupplierService, service.NewCategoryService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewProductHandler, handler.NewSupplierHandler, handler.NewCategoryHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("demo-server"))
}
