services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: niveau_usr
      POSTGRES_PASSWORD: niveau_pwd
      POSTGRES_DB: niveau_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
  cache-redis:
    image: redis:6-alpine
    hostname: cache-redis
    # volumes:
    #   - ./data/redis/cache/:/data
    #   - ./conf/redis/cache/redis.conf:/etc/redis/redis.conf
    ports:
      - 6350:6379
    command: ["redis-server", "/etc/redis/redis.conf"]
volumes:
  pg_data:
    driver: local
